version: '2'

services:
  server:
    image: jetbrains/teamcity-server:2017.1.5
    volumes:
      - ./data/server_data:/data/teamcity_server/datadir
      - ./data/teamcity_server_logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  agent:
    image: jetbrains/teamcity-agent:2017.1.5
    volumes:
      - ./data/agent_conf:/data/teamcity_agent/conf
    environment:
      - SERVER_URL=server:8111
